nav:
  - Overview: index.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - About:
      - "about/*"
  - Usage:
      - "usage/main-view.md"
      - "usage/*"
  - Memories:
      - "memories/*"
  - Configuration:
    - "configurations/*"
  - Integrations:
      - "integrations/mobile-apps.md"
      - "integrations/*"
  - Infrastructure:
      - backup.md
      - "infrastructure/*"
  - "*"